import { AccountSubjectCategoryEnum } from "@/5.shared/enums";
import { AccountAddRequest } from "@/5.shared/types";

export const Account: AccountAddRequest = {
  category: AccountSubjectCategoryEnum.CAPITAL,
  activated: true,
  code: "",
  name: "",
};

export const AutoSet: AccountAddRequest[] = [
  {
    category: "ASSET",
    code: "100-100",
    name: "현금",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-101",
    name: "당좌예금",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-102",
    name: "보통예금",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-103",
    name: "정기예금",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-104",
    name: "정기적금",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-105",
    name: "유가증권",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-106",
    name: "외상매출금",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-107",
    name: "받을어음",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-108",
    name: "단기대여금",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-109",
    name: "장기대여금",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-110",
    name: "미수금",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-111",
    name: "미수수익",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-112",
    name: "자산",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-113",
    name: "선급비용",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-114",
    name: "선급비용",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-115",
    name: "상품",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-116",
    name: "제품",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-117",
    name: "원재료",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-118",
    name: "재공품",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-119",
    name: "반제품",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-120",
    name: "투자부동산",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-121",
    name: "임차보증금",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-122",
    name: "토지",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-123",
    name: "건물",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-124",
    name: "구축물",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-125",
    name: "비품",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-126",
    name: "기계장치",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-127",
    name: "차량운반구",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-128",
    name: "건설중인 자산",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-129",
    name: "영업권",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-130",
    name: "산업재산권",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-131",
    name: "광업권",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-132",
    name: "개발비",
    activated: true,
  },
  {
    category: "ASSET",
    code: "100-133",
    name: "소프트웨어",
    activated: true,
  },
  {
    category: "DEBT",
    code: "101-200",
    name: "외상매입금",
    activated: true,
  },
  {
    category: "DEBT",
    code: "101-201",
    name: "지급어음",
    activated: true,
  },
  {
    category: "DEBT",
    code: "101-202",
    name: "단기차입금",
    activated: true,
  },
  {
    category: "DEBT",
    code: "101-203",
    name: "장기차입금",
    activated: true,
  },
  {
    category: "DEBT",
    code: "101-204",
    name: "미지급금",
    activated: true,
  },
  {
    category: "DEBT",
    code: "101-205",
    name: "미지급비용",
    activated: true,
  },
  {
    category: "DEBT",
    code: "101-206",
    name: "미지급세금",
    activated: true,
  },
  {
    category: "DEBT",
    code: "101-207",
    name: "예수금",
    activated: true,
  },
  {
    category: "DEBT",
    code: "101-208",
    name: "퇴직급여충당부재",
    activated: true,
  },
  {
    category: "DEBT",
    code: "101-209",
    name: "선수금",
    activated: true,
  },
  {
    category: "DEBT",
    code: "101-210",
    name: "선수수익",
    activated: true,
  },
  {
    category: "CAPITAL",
    code: "101-300",
    name: "자본금",
    activated: true,
  },
  {
    category: "CAPITAL",
    code: "101-301",
    name: "이익잉여금",
    activated: true,
  },
  {
    category: "REVENUE",
    code: "201-100",
    name: "매출",
    activated: true,
  },
  {
    category: "REVENUE",
    code: "201-101",
    name: "이자수익",
    activated: true,
  },
  {
    category: "REVENUE",
    code: "201-102",
    name: "배당금수익",
    activated: true,
  },
  {
    category: "REVENUE",
    code: "201-103",
    name: "수수료수익",
    activated: true,
  },
  {
    category: "REVENUE",
    code: "201-104",
    name: "임대료",
    activated: true,
  },
  {
    category: "REVENUE",
    code: "201-105",
    name: "유형자산처분이익",
    activated: true,
  },
  {
    category: "REVENUE",
    code: "201-106",
    name: "투자자산처분이익",
    activated: true,
  },
  {
    category: "REVENUE",
    code: "201-107",
    name: "대손충당금환입",
    activated: true,
  },
  {
    category: "REVENUE",
    code: "201-108",
    name: "법인세환급액",
    activated: true,
  },
  {
    category: "REVENUE",
    code: "201-109",
    name: "외환차익",
    activated: true,
  },
  {
    category: "REVENUE",
    code: "201-110",
    name: "외화환산이익",
    activated: true,
  },
  {
    category: "REVENUE",
    code: "201-111",
    name: "사채상환이익",
    activated: true,
  },
  {
    category: "REVENUE",
    code: "201-112",
    name: "잡이익",
    activated: true,
  },
  {
    category: "REVENUE",
    code: "201-113",
    name: "보험차익",
    activated: true,
  },
  {
    category: "REVENUE",
    code: "201-114",
    name: "자산수증이익",
    activated: true,
  },
  {
    category: "REVENUE",
    code: "201-115",
    name: "채무면제이익",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-200",
    name: "매출원가",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-201",
    name: "급여",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-202",
    name: "퇴직급여",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-203",
    name: "복리후생비",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-204",
    name: "임차료",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-205",
    name: "접대비",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-206",
    name: "보험료",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-207",
    name: "세금과공과",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-208",
    name: "여비교통비",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-209",
    name: "수도광열비",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-210",
    name: "광고선전비",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-211",
    name: "통신비",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-212",
    name: "차량유지비",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-213",
    name: "교육훈련비",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-214",
    name: "도서인쇄비",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-215",
    name: "연구비",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-216",
    name: "경상개발비",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-217",
    name: "수선비",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-218",
    name: "운반비",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-219",
    name: "감가상각비",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-220",
    name: "대손상각비",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-221",
    name: "소모품비",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-222",
    name: "이자비용",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-223",
    name: "지급수수료",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-224",
    name: "유형자산 처분손실",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-225",
    name: "투자자산 처분손실",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-226",
    name: "외환차손",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-227",
    name: "외화환산손실",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-228",
    name: "사채상환손실",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-229",
    name: "매출채권처분손실",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-230",
    name: "법인세추납액",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-231",
    name: "기부금",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-232",
    name: "잡손실",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-233",
    name: "재해손실",
    activated: true,
  },
  {
    category: "EXPENSE",
    code: "202-234",
    name: "법인세비용",
    activated: true,
  },
];